format = """\
$os\
[](fg:color_white bg:color_choco_dark)\
$time\
[](fg:color_choco_dark bg:color_mint)\
$directory\
[](fg:color_mint bg:color_kubernetes)\
$kubernetes\
[](fg:color_kubernetes bg:color_blue)\
$git_branch\
$git_status\
$git_metrics\
[](fg:color_blue bg:color_golang)\
$golang\
[](fg:color_golang bg:color_nodejs)\
$nodejs\
[](fg:color_nodejs)
$character\
"""

palette = "walnuts-chocomint"

[palettes.walnuts-chocomint]
color_black = "#26201D"
color_white = "#EFE7E0"
color_choco_light = "#F1CABA"
color_choco = "#957c72"
color_choco_dark = "#695851"
color_mint = "#95e6d2"
color_mint_dark = "#334E48"
color_blue = "#57bdf3"
color_purple = "#B295E6"
color_kubernetes = "#326de6"
color_golang = "#6ad7e5"
color_nodejs = "#87cf30"

[os]
format = "[ $symbol]($style)"
style = "bg:color_white fg:color_black"
disabled = false

[os.symbols]
Windows = " "

[time]
disabled = false
time_format = "%R"                                 # Hour:Minute Format
style = "bg:color_choco_dark fg:color_choco_light"
format = '[ 󱑍 $time ]($style)'

[directory]
format = "[ ﱮ $path ]($style)"
style = "fg:color_mint_dark bg:color_mint"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:color_black bg:color_blue"

[git_status]
format = '[$all_status]($style)'
style = "fg:color_black bg:color_blue"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:color_black bg:color_blue"
deleted_style = "fg:bright-red bg:235"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[  $duration ]($style)"
style = "fg:bright-white bg:18"

[character]
success_symbol = '[❯](bold green) '
error_symbol = '[❯](#E84D44) '

[kubernetes]
format = '[ 󱃾 $symbol ]($style)'
disabled = false
symbol = "$cluster"
style = "fg:color_white bg:color_kubernetes"

[golang]
format = '[  $version ]($style)'
style = "fg:color_mint_dark bg:color_golang"

[nodejs]
format = '[ 󰎙 $version ]($style)'
style = "fg:color_mint_dark bg:color_nodejs"
